// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNlbJOnIq98Eeq7l5B2cTBRjoAFNRcYbE',
    appId: '1:126871980784:web:f864089728c2c7e7935035',
    messagingSenderId: '126871980784',
    projectId: 'velhos-medicamentos',
    authDomain: 'velhos-medicamentos.firebaseapp.com',
    storageBucket: 'velhos-medicamentos.firebasestorage.app',
    measurementId: 'G-NLK8K971DM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv7JwWvxrby4tUZjPLZYcAav7pAgUSdT0',
    appId: '1:126871980784:android:a7c5b1fa997cd8f1935035',
    messagingSenderId: '126871980784',
    projectId: 'velhos-medicamentos',
    storageBucket: 'velhos-medicamentos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNZ9AU-Y8KX5QDZT4js1TSikjW3ypzoiU',
    appId: '1:126871980784:ios:a72cc5fb45dbf498935035',
    messagingSenderId: '126871980784',
    projectId: 'velhos-medicamentos',
    storageBucket: 'velhos-medicamentos.firebasestorage.app',
    iosBundleId: 'com.example.medicamentos',
  );
}
